version: '{branch}-{build}'

environment:
  matrix:
    # Tip: sed -nre 's|.*Qt/.*/|    - QTDIR: &|p' | tr '/' '\' | sort -nt. -k1.20,1 -k2,2 -k3
    - QTDIR: C:\Qt\5.3\mingw482_32
    - QTDIR: C:\Qt\5.3\msvc2013_opengl
    - QTDIR: C:\Qt\5.3\msvc2013_64_opengl
    - QTDIR: C:\Qt\5.4\mingw491_32
    - QTDIR: C:\Qt\5.4\msvc2013_opengl
    - QTDIR: C:\Qt\5.4\msvc2013_64_opengl
    - QTDIR: C:\Qt\5.5\mingw492_32
    - QTDIR: C:\Qt\5.5\msvc2013
    - QTDIR: C:\Qt\5.5\msvc2013_64
    - QTDIR: C:\Qt\5.6\mingw49_32
    - QTDIR: C:\Qt\5.6\msvc2013
    - QTDIR: C:\Qt\5.6\msvc2013_64
    - QTDIR: C:\Qt\5.6\msvc2015
    - QTDIR: C:\Qt\5.6\msvc2015_64
    - QTDIR: C:\Qt\5.7\mingw53_32
    - QTDIR: C:\Qt\5.7\msvc2013
    - QTDIR: C:\Qt\5.7\msvc2013_64
    - QTDIR: C:\Qt\5.7\msvc2015
    - QTDIR: C:\Qt\5.7\msvc2015_64
    - QTDIR: C:\Qt\5.8\mingw53_32
    - QTDIR: C:\Qt\5.8\msvc2013
    - QTDIR: C:\Qt\5.8\msvc2013_64
    - QTDIR: C:\Qt\5.8\msvc2015
    - QTDIR: C:\Qt\5.8\msvc2015_64
    - QTDIR: C:\Qt\5.9.4\mingw53_32
    - QTDIR: C:\Qt\5.9.4\msvc2013_64
    - QTDIR: C:\Qt\5.9.4\msvc2015
    - QTDIR: C:\Qt\5.9.4\msvc2015_64
    - QTDIR: C:\Qt\5.10.1\mingw53_32
    - QTDIR: C:\Qt\5.10.1\msvc2013_64
    - QTDIR: C:\Qt\5.10.1\msvc2015
    - QTDIR: C:\Qt\5.10.1\msvc2015_64

configuration:
  - debug
  - release

install:
  - C:\cygwin\bin\find C:\Qt -maxdepth 2 -type d
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - qmake -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - '%make%'
  - cd %APPVEYOR_BUILD_FOLDER%-build/pkg/nsis
  # Qt 5.6.2 windeployqt issue (https://bugreports.qt.io/browse/QTBUG-56616)
  # Remove the following SKIP_NSIS concept if/when AppVeyor gets Qt 5.6.3+
  - if %QTDIR%==C:\Qt\5.6\mingw49_32 if %CONFIGURATION%==debug set SKIP_NSIS=QTBUG-56616
  - if defined SKIP_NSIS ( echo Skipping NSIS due to %SKIP_NSIS% ) else %make% nsis

after_build:
  # Add a link to the build output within the source directory. This is needed because AppVeyor does
  # not support extracting artifacts from out-of-source build directories. See 'artifacts' below.
  - mklink %APPVEYOR_BUILD_FOLDER%\Bipolar.exe %APPVEYOR_BUILD_FOLDER%-build\src\%CONFIGURATION%\Bipolar.exe
  - mklink /D %APPVEYOR_BUILD_FOLDER%\nsis %APPVEYOR_BUILD_FOLDER%-build\pkg\nsis

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - if not %CONFIGURATION%==debug %make% check 'TESTARGS="-o -,txt -o tests.xml,xunitxml"'
  - if %QTDIR:msvc=%==%QTDIR% ( set "BIPOLAR_TEST_LOCALE=german" ) else set "BIPOLAR_TEST_LOCALE=de-DE"
  - if not %CONFIGURATION%==debug %make% check 'TESTARGS="-o tests-de.xml,xunitxml"'

after_test:
  - ps: >
      if ($env:CONFIGURATION -ne 'debug') {
        (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path tests.xml))
      }
  - ps: >
      if ($env:CONFIGURATION -ne 'debug') {
        (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path tests-de.xml))
      }

artifacts:
  - path: Bipolar.exe
    name: Application
  - path: nsis\Bipolar-*.exe
    name: Installer

deploy:
  - provider: GitHub
    artifact: Installer
    auth_token:
      secure: d5mVeOvqlPCzZHF7yx8seNWDzICvIwNtpZqmbMpzOGp8DLKP/SDl4AD8i6UX068c
    on:
      appveyor_repo_tag: true
      configuration: release
      QTDIR: C:\Qt\5.9.2\msvc2015_64

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/99c9fd317df850e7beb8
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
