version: '{branch}-{build}'

environment:
  matrix:
    - QTDIR: C:\Qt\5.3\mingw482_32
    - QTDIR: C:\Qt\5.3\msvc2013_opengl
    - QTDIR: C:\Qt\5.3\msvc2013_64_opengl
    - QTDIR: C:\Qt\5.4\mingw491_32
    - QTDIR: C:\Qt\5.4\msvc2013_opengl
    - QTDIR: C:\Qt\5.4\msvc2013_64_opengl
    - QTDIR: C:\Qt\5.5\mingw492_32
    - QTDIR: C:\Qt\5.5\msvc2013
    - QTDIR: C:\Qt\5.5\msvc2013_64
    - QTDIR: C:\Qt\5.6\mingw49_32
    - QTDIR: C:\Qt\5.6\msvc2013
    - QTDIR: C:\Qt\5.6\msvc2013_64
    - QTDIR: C:\Qt\5.6\msvc2015
    - QTDIR: C:\Qt\5.6\msvc2015_64
    - QTDIR: C:\Qt\5.7\mingw53_32
    - QTDIR: C:\Qt\5.7\msvc2013
    - QTDIR: C:\Qt\5.7\msvc2013_64
    - QTDIR: C:\Qt\5.7\msvc2015
    - QTDIR: C:\Qt\5.7\msvc2015_64

configuration:
  - debug
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - qmake -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - '%make%'
  - cd %APPVEYOR_BUILD_FOLDER%-build/pkg/nsis
  - '%make% nsis'

after_build:
  # Add a link to the build output within the source directory. This is needed because AppVeyor does
  # not support extracting artifacts from out-of-source build directories. See 'artifacts' below.
  - mklink %APPVEYOR_BUILD_FOLDER%\Bipolar.exe %APPVEYOR_BUILD_FOLDER%-build\src\%CONFIGURATION%\Bipolar.exe
  - mklink /D %APPVEYOR_BUILD_FOLDER%\nsis %APPVEYOR_BUILD_FOLDER%-build\pkg\nsis

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - if not %CONFIGURATION%==debug %make% check
  - if %QTDIR:msvc=%==%QTDIR% ( set "BIPOLAR_TEST_LOCALE=german" ) else set "BIPOLAR_TEST_LOCALE=de-DE"
  - if not %CONFIGURATION%==debug %make% check TESTARGS=-silent

artifacts:
  - path: Bipolar.exe
    name: Application
  - path: nsis\Bipolar-*.exe
    name: Installer

deploy:
  - provider: GitHub
    artifact: Installer
    auth_token:
      secure: d5mVeOvqlPCzZHF7yx8seNWDzICvIwNtpZqmbMpzOGp8DLKP/SDl4AD8i6UX068c
    on:
      appveyor_repo_tag: true
      configuration: release
      QTDIR: C:\Qt\5.7\msvc2015_64

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/99c9fd317df850e7beb8
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
