version: '{branch}-{build}'

install:
  - choco install openssl -ia '/DIR=C:\OpenSSL-Win32' -version 1.0.2.20150731 --x86

build_script:
  - build.cmd

artifacts:
  - path: build\qtbase\lib\Qt5Network.dll
