version: '{branch}-{build}'

install:
  - ps: (new-object net.webclient).DownloadFile('http://code.x2go.org/releases/binary-win32/3rd-party/Win32OpenSSL/Win32OpenSSL-1_0_1g.exe', 'Win32OpenSSL-1_0_1g.exe')
  - Win32OpenSSL-1_0_1g.exe /silent

build_script:
  - build.cmd

artifacts:
  - path: build\qtbase\lib\Qt5Network.dll
