language: cpp

os: osx

compiler: clang

xcode_sdk: macosx10.8

before_install:
  - xcodebuild -showsdks
  - env

install:
  - pushd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
  - curl -L https://github.com/AaronWallace/MacOSX_SDKs/tarball/master | tar xvz MacOSX10.8.sdk
  - popd
  - 'find /Applications/Xcode.app/Contents/Developer/Platforms -name *crt1*'

before_script:
  - xcodebuild -showsdks
  - /usr/bin/xcodebuild -sdk macosx10.8 -version Path
  - /usr/bin/xcodebuild -sdk macosx10.8 -version

script:
  - ./build.sh
