language: cpp

compiler:
  - clang
  - gcc

env:
  - QTVER=ust # Ubuntu SDK Team (Qt 5.x).
  - QTVER=502
  - QTVER=511
  - QTVER=521
  - QTVER=532
  - QTVER=541
  - QTVER=55

before_install:
  - \[ $QTVER == 'ust' ]; || sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - \[ $QTVER != 'ust' ]; || sudo add-apt-repository -y ppa:beineri/opt-qt$QTVER
  - sudo apt-get -qy update

install:
  - sudo apt-get -qy install cppcheck
  - if [ $QTVER != '502' ]; then export PKG_VER=`echo $QT_VER | cut -b1-2`; fi
  - \[ $QTVER == 'ust' ]; || sudo apt-get -qy install qt${PKG_VER}base qt${PKG_VER}xmlpatterns; fi
  - \[ $QTVER != 'ust' ]; || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev

before_script:
  - cppcheck --error-exitcode=1 --quiet .
  - qmake -qt=qt5 -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release

script:
  - make all && make check

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b8ecf97afdf630edcec
    on_success: change
    on_failure: always
    on_start: never
