language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt5-qmake qtbase5-dev

before_script:
  - pushd test
  - qmake -qt=qt5
  - popd

script:
  - pushd test
  - pwd
  - ls -l
  - find . -name *.dat || true
  - find . -name golden* || true
  - find . -name testdata || true
  - updatedb && locate golden_message || true
  - make && make check
  - popd
