language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cppcheck qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev

before_script:
  - cppcheck --error-exitcode=1 --quiet .
  - qmake -qt=qt5 -Wall -Wlogic -Wparser CONFIG+=debug_and_release

script:
  - make all && make check

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b8ecf97afdf630edcec
    on_success: change
    on_failure: always
    on_start: never
