language: cpp

os:
 #- linux
  - osx

compiler:
  - clang
  - gcc

env:
  - QTVER=ust # Ubuntu SDK Team (Qt 5.x).
  - QTVER=502
  - QTVER=511
  - QTVER=521
  - QTVER=532
  - QTVER=541
  - QTVER=55

matrix:
  allow_failures:
    - env: QTVER=55 # Qt 5.5 not supported yet (issue #56).
    #- os: osx # Work in progress.
  exclude:
    - compiler: clang # QTBUG-32100
      env: QTVER=ust
    - compiler: clang # QTBUG-32100
      env: QTVER=502

before_install:
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER == ust ]] || sudo add-apt-repository -y ppa:beineri/opt-qt$QTVER'
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER != ust ]] || sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa'
  - '[[ "$TRAVIS_OS_NAME" != linux ]] || sudo apt-get -qy update'
  - '[[ "$TRAVIS_OS_NAME" != osx   ]] || brew upgrade'

install:
  - '[[ "$TRAVIS_OS_NAME" != linux ]] || sudo apt-get -qy install cppcheck'
  - if [ $QTVER != 502 ]; then export SHORT_VER=`echo $QTVER | cut -b1-2`; fi
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER == ust ]] || sudo apt-get -qy install qt${SHORT_VER}base qt${SHORT_VER}xmlpatterns'
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER != ust ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - '[[ "$TRAVIS_OS_NAME" != osx   ]] || brew install cppcheck qt5'

before_script:
  - cppcheck --error-exitcode=1 --quiet .
  - if [[ "$TRAVIS_OS_NAME" == linux && "$CXX" == clang++ ]; then export QMAKESPEC=linux-clang; fi
  - if [[ "$TRAVIS_OS_NAME" == linux && "$CXX" == gcc     ]; then export QMAKESPEC=linux-g++;   fi
  - if [[ "$TRAVIS_OS_NAME" == osx   && "$CXX" == clang++ ]; then export QMAKESPEC=macx-clang;  fi
  - if [[ "$TRAVIS_OS_NAME" == osx   && "$CXX" == gcc     ]; then export QMAKESPEC=macx-g++;    fi
  - if [[ "$TRAVIS_OS_NAME" == linux && $QTVER == ust ]]; then export QMAKE_VER=-qt=qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == linux && $QTVER == 502 ]]; then export SHORT_VER=5; fi
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER == ust ]] || . /opt/qt$SHORT_VER/bin/qt$SHORT_VER-env.sh'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - pushd "$TRAVIS_BUILD_DIR-build"
  - qmake $QMAKE_VER -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"
  - popd

script:
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 all
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 check TESTARGS=-silent

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b8ecf97afdf630edcec
    on_success: change
    on_failure: always
    on_start: never
