language: cpp

os: osx

install:
  - find / -type d -name SDKs
  - find / -type d -name SDK -exec ls {}\;
  - locate SDKs
  - ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
  - ls /Volumes
  - ls '/Volumes/VMware Shared Folders'
  - sudo cp -a
    /Volumes/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs

script:
  - ./build.sh
