language: cpp

os: osx

compiler: clang

before_install:
  - xcodebuild -showsdks
  - env

install:
  - >
    curl -sL https://github.com/AaronWallace/MacOSX_SDKs/tarball/ba4d5b3 | tar xvz
    --directory /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    --strip-components=1 AaronWallace-MacOSX_SDKs-ba4d5b3/MacOSX10.8.sdk
  - 'find /Applications/Xcode.app/Contents/Developer/Platforms -name *crt1*'

before_script:
  - xcodebuild -showsdks
  - /usr/bin/xcodebuild -sdk macosx10.8 -version Path
  - /usr/bin/xcodebuild -sdk macosx10.8 -version

script:
  - ./build.sh
