language: cpp

os: osx

xcode_sdk: macosx10.8

before_install:
  - xcodebuild -showsdks
  - env

install:
  - pushd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
  - wget https://github.com/phracker/MacOSX-SDKs/releases/download/MacOSX10.11.sdk/MacOSX10.8.sdk.tar.xz
  - tar xJf MacOSX10.8.sdk.tar.xz
  - popd

before_script:
  - xcodebuild -showsdks

script:
  - ./build.sh
