language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - QTVER=ust # Ubuntu SDK Team (Qt 5.x).
  - QTVER=502 # Ubuntu only.
  - QTVER=511 # Ubuntu only.
  - QTVER=521 # OSX and Ubuntu.
  - QTVER=532 # OSX and Ubuntu.
  - QTVER=542 # Ubuntu only.
  - QTVER=551 # OSX and Ubuntu.

matrix:
  exclude:
    - { os: osx, env: QTVER=ust }
    - { os: osx, env: QTVER=502 }
    - { os: osx, env: QTVER=511 }
    - { os: osx, env: QTVER=542 }
    - { compiler: clang, env: QTVER=ust } # QTBUG-32100
    - { compiler: clang, env: QTVER=502 } # QTBUG-32100

before_install:
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER == ust ]] || sudo add-apt-repository -y ppa:beineri/opt-qt$QTVER'
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER != ust ]] || sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa'
  - '[[ "$TRAVIS_OS_NAME" != linux ]] || sudo apt-get -qy update'
  - '[[ "$TRAVIS_OS_NAME" != osx   || $QTVER == 532 ]] || brew update'

install:
  - '[[ "$TRAVIS_OS_NAME" != linux ]] || sudo apt-get -qy install cppcheck'
  - if [ $QTVER != 502 ]; then export SHORT_VER=`echo $QTVER | cut -b1-2`; fi
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER == ust ]] || sudo apt-get -qy install qt${SHORT_VER}base qt${SHORT_VER}xmlpatterns'
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER != ust ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - '[[ "$TRAVIS_OS_NAME" != osx   || $QTVER == 521 ]] || brew install cppcheck qt5'
  - '[[ "$TRAVIS_OS_NAME" != osx   || $QTVER != 521 ]] || brew install cppcheck homebrew/versions/qt52'
  - '[[ "$TRAVIS_OS_NAME" != osx   || $QTVER == 521 ]] || brew link --force qt5'
  - '[[ "$TRAVIS_OS_NAME" != osx   || $QTVER != 521 ]] || brew link --force homebrew/versions/qt52'

before_script:
  - cppcheck --error-exitcode=1 --quiet .
  - if [[ "$TRAVIS_OS_NAME" == linux && "$CXX" == clang++ ]]; then export QMAKESPEC=linux-clang; fi
  - if [[ "$TRAVIS_OS_NAME" == linux && "$CXX" == g++     ]]; then export QMAKESPEC=linux-g++;   fi
  - if [[ "$TRAVIS_OS_NAME" == osx   && "$CXX" == clang++ ]]; then export QMAKESPEC=macx-clang;  fi
  - if [[ "$TRAVIS_OS_NAME" == osx   && "$CXX" == g++     ]]; then export QMAKESPEC=macx-g++;    fi
  - if [[ "$TRAVIS_OS_NAME" == linux && $QTVER == ust ]]; then export QMAKE_VER=-qt=qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == linux && $QTVER == 502 ]]; then export SHORT_VER=5; fi
  - '[[ "$TRAVIS_OS_NAME" != linux || $QTVER == ust ]] || . /opt/qt$SHORT_VER/bin/qt$SHORT_VER-env.sh'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - pushd "$TRAVIS_BUILD_DIR-build"
  - qmake $QMAKE_VER -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"
  - popd

script:
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 all
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 check
  - '[ "$TRAVIS_OS_NAME" != osx ] || make -C "$TRAVIS_BUILD_DIR-build/pkg/osx" dmg'

deploy:
  provider: releases
  api_key: $RELEASES_API_KEY
  file: $TRAVIS_BUILD_DIR-build/pkg/$TRAVIS_OS_NAME/Bipolar-0.5.1.$TRAVIS_BUILD_NUMBER.dmg
  on:
    condition: '"$TRAVIS_OS_NAME" == osx && "$CXX" == clang++ && "$QTVER" == 551'
    tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b8ecf97afdf630edcec
    on_success: change
    on_failure: always
    on_start: never
