language: cpp

os: osx

compiler: clang

xcode_sdk: macosx10.8

before_install:
  - xcodebuild -showsdks
  - env

install:
  - pushd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
  - wget https://github.com/phracker/MacOSX-SDKs/releases/download/MacOSX10.11.sdk/MacOSX10.8.sdk.tar.xz
  - tar xJf MacOSX10.8.sdk.tar.xz
  - popd

before_script:
  - xcodebuild -showsdks
  - /usr/bin/xcodebuild -sdk macosx10.8 -version Path
  - /usr/bin/xcodebuild -sdk macosx10.8 -version

script:
  - export C_INCLUDE_PATH=/Developer/SDKs/MacOSX10.8.sdk/usr/include
  - export LIBRARY_PATH=/Developer/SDKs/MacOSX10.8.sdk/usr/lib
  - ./build.sh
